// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the "Connect to Firebase" guide to view and copy your
// own Firebase config object.

// If you don't see your Firebase config object below, right-click on the "Firebase"
// icon in the left-hand side menu and select the "Add Firebase" command in the
// command pallet.

// To connect to a different Firebase project, right-click on the "Firebase"
// icon in the left-hand side menu and select the "Connect to a different project"
// command in the command pallet.

export const firebaseConfig = {
  "projectId": "studio-2563067287-258f7",
  "appId": "1:90579608357:web:099e07730b25262c6d30cc",
  "apiKey": "AIzaSyCSoueFjuNnF5ilFoMQBTp6yWEfKp-6kjE",
  "authDomain": "studio-2563067287-258f7.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "90579608357"
};
